### ISSUE TITLE
Check table of contents

### ISSUE THREAD

**Issue by RubenVerborgh** [OpenWebslides/BroodjeMartinnovatie#1]
I added a table of contents in c67bdaf50b748108ab1036b9c03f37632614cf5b.

Please check whether you agree, or make changes as you see fit.

**Comment by EstherDeLoof** [comment]
Looks encompassing and logically ordered to me.

Below are some notes on the further specification of the UGent plans. 

I would speak in terms of a two-phase process. First, the focus will be on the versatility of the material, with mostly a single teacher making a set of slides with all the added value of the web. Second, the technical and educational know-how will allow for more co-creation as the pilot projects mature.

Maybe we can also add a comparison between existing software (Slides.com, Office360 etc.) and what we envision. Why do we need additional development and what is the stability on the long term? Not sure how "Geplande ontwikkelingen" and "Online ontwikkeltools" will function in that sequence.

For the pilot projects, I would also indicate which profiles we think might be suited to make the transition (e.g., technically skilled teachers, people who start a new course from scratch...) and the difficulties with transferring directly from Powerpoint. We usually get Qs on that topic.

**Comment by RubenVerborgh** [comment]
"Online ontwikkeltools" would be Slides.com, Office360. How it would work: in "Geplande ontwikkelingen", we describe what we want; in the other, we explain why these tools do not have all we want.

=> I'll add a new subsection at the end about transitioning!
